/* Generated By:JavaCC: Do not edit this line. GrammarHbVarConstants.java */
package grammarHbVar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GrammarHbVarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int nextline = 4;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int HYPHENE = 8;
  /** RegularExpression Id. */
  int CHANGETO = 9;
  /** RegularExpression Id. */
  int PARENTHESIS = 10;
  /** RegularExpression Id. */
  int SYMBOLS = 11;
  /** RegularExpression Id. */
  int DOLLAR = 12;
  /** RegularExpression Id. */
  int UNEXPECTED = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<DIGIT>",
    "<NUMBER>",
    "<LETTER>",
    "<HYPHENE>",
    "<CHANGETO>",
    "<PARENTHESIS>",
    "<SYMBOLS>",
    "<DOLLAR>",
    "<UNEXPECTED>",
    "\"***\"",
    "\"or\"",
    "\"OR\"",
    "\"Or\"",
    "\"AND\"",
    "\"and\"",
    "\"And\"",
    "\"Hb\"",
    "\"Glu\"",
    "\"Asp\"",
    "\"Ala\"",
    "\"Arg\"",
    "\"Asn\"",
    "\"Cys\"",
    "\"Gln\"",
    "\"Gly\"",
    "\"His\"",
    "\"Ile\"",
    "\"Leu\"",
    "\"Lys\"",
    "\"Met\"",
    "\"Phe\"",
    "\"Pro\"",
    "\"Ser\"",
    "\"Thr\"",
    "\"Trp\"",
    "\"Tyr\"",
    "\"Val\"",
    "\"Ggamma\"",
    "\"Agamma\"",
    "\"delta\"",
    "\"beta\"",
    "\"alpha1\"",
    "\"alpha2\"",
    "\"replaced with\"",
    "\"modified C\"",
    "\"terminal sequence\"",
    "\"COOH\"",
    "\"Stop\"",
    "\"STOP\"",
    "\"stop\"",
    "\"->0\"",
    "\"and inserted\"",
    "\"AND inserted\"",
    "\"And inserted\"",
    "\"inserted between\"",
    "\"codons\"",
  };

}
